/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentation.Components.ViewObjects;

import BE.IViewObjectBE;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

/**
 *
 * @author Brobak
 */
public abstract class ViewObject extends javax.swing.JPanel {
    IViewObjectBE viewObjectBE; 
    JLabel lblName;
    
    /**
     * Creates new form ViewObject
     * @param viewObjectBE
     */
    protected ViewObject(IViewObjectBE viewObjectBE) {
        initComponents();
        setBorder(BorderFactory.createLineBorder(Color.BLACK, 5));
        this.viewObjectBE = viewObjectBE;
        
        fillData();
    }
    
    protected abstract void fillData();
    
    public abstract void refreshViewObject();
     
    public IViewObjectBE getViewObjectBE(){
        return viewObjectBE;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


}
