/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentation.Components.ViewObjects;

import BLL.IViewObjectObserver;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

/**
 *
 * @author Brobak
 */
public abstract class ViewObject extends javax.swing.JPanel {

    ArrayList<IViewObjectObserver> observers;
    
    /**
     * Creates new form ViewObject
     */
    public ViewObject() {
        initComponents();
        observers = new ArrayList<>();
        
    }
    
    public void addMouseObserver(IViewObjectObserver observer){
        observers.add(observer);
    }
    
    private void runObservers(){
        for(IViewObjectObserver observer: observers)
            observer.notifyObserver();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private class myMouseAdapter extends MouseAdapter{

        @Override
        public void mousePressed(MouseEvent e) {
            runObservers();
        }
        
    }

}
