/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentation.Components;

import BE.Alarm;
import BE.Story;
import BE.TimeSheetList;
import BE.Time_Sheet;
import BLL.Alarm_AccessLink;
import BLL.IObserver;
import BLL.TimeSheet_AccessLink;
import Presentation.Components.ViewObjects.ViewObject;
import Presentation.Components.ViewObjects.ViewObjectAlarm;
import Presentation.Components.ViewObjects.ViewObjectFactory;
import Presentation.Components.ViewObjects.ViewObjectTimeSheet;
import Presentation.Frames.MainFrame;
import Presentation.MyConstants;
import java.awt.BorderLayout;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Poul Nielsen
 */
public class AproveTimeSheet extends javax.swing.JPanel {
    TimeSheet_AccessLink tsa;
    Alarm_AccessLink aal;
    ViewObjectFactory vof;
    TabView tv;
    MainFrame parent;
    ListPanel alarmList, timeSheetList;
    myObserverListener myObserver;
    ArrayList<Alarm> openAlarms; 
    /**
     * Creates new form AproveTimeSheet
     * @param parent
     */
    public AproveTimeSheet(MainFrame parent, int firemanId) {
        initComponents();
        setLayout(new BorderLayout());
        this.parent = parent;
        myObserver = new myObserverListener();
        openAlarms = new ArrayList<>();
        try {
            tsa = new TimeSheet_AccessLink();
            aal = new Alarm_AccessLink();
            vof = new ViewObjectFactory();
        } catch (IOException ex) {
          
        }
        createTabs(firemanId);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * creates the tabview to be used and puts in the alarms relevenat to the given fireman
     * @param firemanId the firman id for the teamleader to search for unapproved runs for.
     */
    private void createTabs(int firemanId)
    {
        alarmList = getAlarmByFiremanId(firemanId);
        alarmList.addSelectionObserver(myObserver);
        
        tv = new TabView();
        tv.addNewTab("alarm", alarmList, parent.getWidth());
        
        add(tv, BorderLayout.CENTER);
        validate();
        repaint();
    }
    
    /**
     * creates a new listpanel with all alarms relevant to the teamleader given by his id
     * @param firemanId the id of the teamleader
     * @return a listpanel with alarms.
     */
    protected ListPanel getAlarmByFiremanId(int firemanId)
    {
        ArrayList<Time_Sheet> timeSheet = new ArrayList<Time_Sheet>();
        
        ListPanel list = new ListPanel(parent.getWidth());
        ArrayList<Alarm> alarms = new ArrayList<Alarm>();
        try{
            timeSheet = tsa.getTimeSheetsbyFiremanId(firemanId);
            
            for(Time_Sheet c : timeSheet)
            {
                if(!arrayContainsAlarmId(alarms, c.getAlarmID())){
                    Alarm a = aal.getAlarmById(c.getAlarmID());
                    if ( a != null) alarms.add(a);
                }
            }
       
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database call error: " + ex);
        }
        for(Alarm a : alarms){
                list.addViewObject(ViewObjectFactory.getViewObject(a));
            }
        
        return list;
    }
    
    /**
     * creates an overvies of unaccepted timesheets on a specific alarm
     * in a listpanel.
     * @param alarmId the alarm to create it for
     * @return a listpanel with an overview. and viewobjects to accept
     */
    private ListPanel getTimeSheetByAlarmId(int alarmId)
    {
        ArrayList<Time_Sheet> timeSheet = new ArrayList<Time_Sheet>();
        ArrayList<Time_Sheet> timeSheetStatinsduty = new ArrayList<Time_Sheet>();
        ListPanel list = new ListPanel(parent.getWidth());
        try {
            timeSheet = tsa.getDataForAproval(alarmId);
            timeSheetStatinsduty = tsa.stationsVagt(alarmId);
            //here lays the logic for showing the timesheets order by cars and station duty
            ArrayList<TimeSheetList> timeSheetLists = new ArrayList<>();
            for(Time_Sheet a : timeSheet)
            {
                boolean carFound = false;
                for(TimeSheetList ts : timeSheetLists){
                    if(ts.getCar() != null && ts.getCar().getCarNr() == a.getCar().getCarNr()){
                        carFound = true;
                        populateFiremenViewObject(a, ts);
                        
                    }
                }
                if(!carFound){
                    TimeSheetList tsl = new TimeSheetList(a);
                    populateFiremenViewObject(a, tsl);
                    timeSheetLists.add(tsl);
                    //list.addViewObject(ViewObjectFactory.getViewObject(tsl));
                }
            }
            TimeSheetList v;
            if(timeSheetStatinsduty.size() > 0){
                v = new TimeSheetList(timeSheetStatinsduty.get(0));
                for(Time_Sheet b : timeSheetStatinsduty)
                {
                    v.addStationDuty(b);
                    
                }
                list.addViewObject(ViewObjectFactory.getViewObject(v));
            }
            
            for(TimeSheetList tsl: timeSheetLists){
                list.addViewObject(ViewObjectFactory.getViewObject(tsl));
            }
            Story s = new Story(alarmId);
            list.addViewObject(ViewObjectFactory.getViewObject(s));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database call error: " + ex);
        }
        
        
        return list;
    }

    /**
     * adds the timesheet to the correct array in the timesheet list
     * @param a the timsheet to add
     * @param v the list to add it to.
     */
    private void populateFiremenViewObject(Time_Sheet a, TimeSheetList v) {
        if(a.getPositionID() == MyConstants.TEAM_LEADER.getID())
        {
            v.addTeamLeader(a);
        }
        if(a.getPositionID() == MyConstants.DRIVER.getID())
        {
            v.addDriver(a);
        }
        if(a.getPositionID() == MyConstants.FIREMAN.getID())
        {
            v.addFireman(a);
        }
        
    }

    /**
     * checks if an alarm arraylist contains the given alarm id.
     * @param alarms the list to search in
     * @param alarmID the id to search for
     * @return if it is in there it returns true, false otherwise.
     */
    private boolean arrayContainsAlarmId(ArrayList<Alarm> alarms, int alarmID) {
        for(Alarm a: alarms){
            if(a.getID() == alarmID) return true;
        }
        
        return false;
    }
    
    /**
     * observer to be added to the alarm list to create new tabs when somthing is selected.
     */
    private class myObserverListener implements IObserver{

        @Override
        public void notifyObserver() {
            
        if(alarmList.getSelectedViewObject().getClass() == ViewObjectAlarm.class)
        {
            ViewObjectAlarm voa = (ViewObjectAlarm)alarmList.getSelectedViewObject();
            
            Alarm alarm = voa.getAlarm();
            
            String alarmTitle = voa.getAlarm().getDistination();
            if(!openAlarms.contains(alarm))
            {
                timeSheetList = getTimeSheetByAlarmId(alarm.getID());
                tv.addNewTab(alarmTitle, timeSheetList, parent.getWidth());
                tv.setSelectedComponent(timeSheetList);
                openAlarms.add(alarm);
            }
            
        }
        }
        
    }
    
}

