/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentation.Components;

import Presentation.Components.ViewObjects.ViewObject;
import Presentation.MyColorConstants;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Brobak
 */
public class ListPanel extends javax.swing.JPanel {
    JPanel thisList;
    DefaultListModel model;
    /**
     * Creates new form ListPanel
     */
    public ListPanel() {
        initComponents();
        thisList = this;
        model = new DefaultListModel();
        lstData.setModel(model);
        lstData.setCellRenderer(getClientListRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstData = new javax.swing.JList();

        jScrollPane1.setViewportView(lstData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstData;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Adds a new ViewObject to the lst
     * @param object the ViewObject you want to add to the list
     */
    public void addViewObject(ViewObject object){
        model.addElement(object);
    }
    
    /**
     * Gets the Cell renderer for the list
     * @return 
     */
    private ListCellRenderer getClientListRenderer(){
        ListCellRenderer r =
                new ListCellRenderer() {
                    @Override
                    public Component getListCellRendererComponent(JList list,
                            Object value, int index, boolean isSelected,
                            boolean cellHasFocus)
                    {
                        ViewObject myViewObject = (ViewObject) value;
                        if(isSelected)
                            myViewObject.setBackground(MyColorConstants.LIGHT_BLUE);
                        else
                            myViewObject.setBackground(Color.WHITE);
                        JPanel surroundPanel = new JPanel();
                        surroundPanel.setLayout(new BorderLayout());
                        surroundPanel.add(myViewObject, BorderLayout.CENTER);
                        surroundPanel.setBorder(new EmptyBorder(0, 0, 5, 0));
                        return surroundPanel;
                    }
                };
        
        
        return r;
    }

}
